<?php

echo PHP_VERSION;

echo "<br>";

//ISSO VAI INFORMAR A BARRA DO DIRETORIO, EXEMPLO NO LINUX QUE O BARRA É NORMALMENTE AO CONTRARIO DO WINDOWNS POIS PODE MUDAR O CÓDIGO PARA QUE EVITE O TRABALHO DA DIFERENÇA DE BARRA
echo DIRECTORY_SEPARATOR;

?>